// AUTO-GENERATED by scripts/process-images.mjs — do not edit by hand. Run `npm run images`.
import type { Photo, PhotoPair } from "@/lib/photo-types";

export const photos: Photo[] = [
  {
    "id": "4runner-full-detail",
    "src": "/work/4runner-full-detail-tall.0ff74a6e.webp",
    "width": 1080,
    "height": 1350,
    "alt": "Black Toyota 4Runner after a full detail — mobile detailing in Harrisonburg VA",
    "vehicle": "Toyota 4Runner",
    "service": "Full detail",
    "crops": {
      "wide": {
        "src": "/work/4runner-full-detail-wide.da8ea12b.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAkAA4BaJYwCdAD1eKd9dZoAAOIe7bLW5sE60o3h2x2aPqWdRVH2LVxkzwO4VfCjjow2LT1Brk27VBM0GIQGf4NaAc6dhIlCcskTJyx1AAAA"
      },
      "tall": {
        "src": "/work/4runner-full-detail-tall.0ff74a6e.webp",
        "width": 1080,
        "height": 1350,
        "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JYgC+SBnOuCQ61C+RbDJtjgD4K2RzbPopFdlTQ+a9iD/ObDnVFRgob75UIJY4AVLa2M+BKfLQ8ntfhC2/5ozLt/zbjbVv+9S8wjCxc4Z9K/gWlT1NRHkctDAAAA=="
      },
      "square": {
        "src": "/work/4runner-full-detail-square.a4c40c41.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwAgCdASoQABAAA4BaJbACdGuAAbrtAhHcAAD8pW8ZGDsolbSgbeGtrI3gtsI+Ov+Wffu/lG8At4KNVkCX0KGyf9tWhbdmuhQW1Sb1avQkXDzjwkj7YPp/prkvFb6JBU6UdJfgOIAAAA=="
      }
    }
  },
  {
    "id": "bmw-x3-black",
    "src": "/work/bmw-x3-black-tall.a0e5cd35.webp",
    "width": 1080,
    "height": 1350,
    "alt": "Black BMW X3 after a detail — mobile detailing in Harrisonburg VA",
    "vehicle": "Black BMW X3",
    "service": "Detail",
    "crops": {
      "wide": {
        "src": "/work/bmw-x3-black-wide.3e4d4357.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJZwAAn3EvGPAAAD+g+34Y+fzPvzAuQVgTZnsTIBDW0LqMcdwLXnLZXb/QdesB003zukKhko5CtlZOzEvY46a6YOB8AAA"
      },
      "tall": {
        "src": "/work/bmw-x3-black-tall.a0e5cd35.webp",
        "width": 1080,
        "height": 1350,
        "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZQAFEB7sUBxaHEGzhSAA/gYSmBGlu+Sq/zE/zFq+cIsSLqYyNyLqmTexNE5TWhQcwXj2hCUq99DJYYZiAbJ58gAlBFnG97QaqTAH/Qk+A58X0K+tAL3APe6d/CVfTytBJKzX2oji5AAA"
      },
      "square": {
        "src": "/work/bmw-x3-black-square.f663a509.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQABAAA4BaJYwAD42Q4CbyIufgAAD+wFwyCy4QrK0naUIpj+B771SyKjuo+SqT7GaET+98sAKVcbBg5sLTz4buK2z4yPnG+RtarhWLM/4jBmCtVQarXeQyIEa9uQAA"
      }
    }
  },
  {
    "id": "boat-sealant",
    "src": "/work/boat-sealant-tall.56550df8.webp",
    "width": 1080,
    "height": 1350,
    "alt": "Green wakeboard boat after an inside-and-out detail with polymer paint sealant — mobile detailing in Harrisonburg VA",
    "vehicle": "Boat",
    "service": "Inside & out + polymer paint sealant",
    "crops": {
      "wide": {
        "src": "/work/boat-sealant-wide.bce9778c.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAQCdASoQAAkAA4BaJQBOgBVDi8rgAP04yFYgjjCczYJj3mpIq8IgLwScISYYvjqDMV2fvMtB8J7lX8trEm4q24wBCo3b2MGPrWLDsklwAA=="
      },
      "tall": {
        "src": "/work/boat-sealant-tall.56550df8.webp",
        "width": 1080,
        "height": 1350,
        "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBUegpiwfit9/QWnx0wAyw8Xzcku70/fYdr8ietieJpQojc19lpaIrHxLVfDR3iPHaGxs+Zbl4of9GAPztCdySWeoAz4ZOg/bhk2KhluuyfJ3eHlOTNApYAAAA=="
      },
      "square": {
        "src": "/work/boat-sealant-square.eab37973.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADwAQCdASoQABAAA4BaJZgCdADQj0fr4MwA8UQ+kQU27hjC90b/fXZIxHFpmqlyL0eqSm71z+xR8s86EJo9s+/1Fj50D5vSWCAlirJLv2vjSkbZBw7UlBhnwsjxYkeIm6wAAA=="
      }
    }
  },
  {
    "id": "camry-seat-shampoo",
    "src": "/work/camry-seat-shampoo-tall.7774f33b.webp",
    "width": 1080,
    "height": 1350,
    "alt": "Toyota Camry wheel after a full detail — mobile detailing in Harrisonburg VA",
    "vehicle": "Toyota Camry",
    "service": "Full detail + seat shampoo",
    "crops": {
      "wide": {
        "src": "/work/camry-seat-shampoo-wide.8cfb6722.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAkAA4BaJQBOgCLNLfm3UNgAAPR1ciph3z1v+FLDlyU1H2TD9UoSPOIYF2+/aSB+j2fFfjcGNumol7dHiaQ+EUSy1IAA"
      },
      "tall": {
        "src": "/work/camry-seat-shampoo-tall.7774f33b.webp",
        "width": 1080,
        "height": 1350,
        "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAABQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JYwB3ADKCV0GNFIG8bWjy63YAAP7qDpwCYPB3KmSgOSWaQNoXjDMojbrETo6s8ZgaXIhafMOhz4ndrSZyHRnjg3fn+5GW95agC4601+pSZGq3pFLqfvFINQJfDUPUOaPmV2d/Dbs/yQWz+l2zgAAA"
      },
      "square": {
        "src": "/work/camry-seat-shampoo-square.b1543ebd.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAwAgCdASoQABAAA4BaJQBdgMWvqNPXVpSQAAD+8bb8g7Sbg2hB3P1TdmVe5/+7WHcAmu66f2Z0bv6OlpKdzhu7WyB6dBIqsjGMQCc78BLjNqbE4PU78uRu3HjL5tr/SfFR+Yvc00HCgb4yKbwAAA=="
      }
    }
  },
  {
    "id": "corvette-c8r",
    "src": "/work/corvette-c8r-tall.6c503b02.webp",
    "width": 651,
    "height": 814,
    "alt": "Yellow limited-edition Corvette C8.R after a detail — mobile detailing in Harrisonburg VA",
    "vehicle": "Limited-edition Corvette C8.R",
    "service": "Detail",
    "crops": {
      "wide": {
        "src": "/work/corvette-c8r-wide.f7c59c48.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoQAAkAA4BaJagCdAYsFa0+loBgAP5Ofyt27tpyvFrMHrou7qZmgJqeV3wW/t4XhfKdVX7Nv3OJRM/qlKCKtBaSSSUCVqC+6hOPr6doNlXV2BNjiKmkXrY9gAA="
      },
      "tall": {
        "src": "/work/corvette-c8r-tall.6c503b02.webp",
        "width": 651,
        "height": 814,
        "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JaAAATvDUs/fdY6pXFuHqAAD+7M1W7vfw+va3pW6WMglmKSaeq8lqIJcf8zmKefJt9soROXRAweCDlp6o5Bsp+2e+iPvdqgkFkNJqszgKbK+ncbkOiks10fC4hg40sXzyuJELyLYYPKVTRUAAAA=="
      },
      "square": {
        "src": "/work/corvette-c8r-square.2afd9f46.webp",
        "width": 814,
        "height": 814,
        "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAwAgCdASoQABAAA4BaJbAC7AYuHLleOwQ7AAD+5ShuV9blPR1Y8+QzansH3P0njTkNk1CwTrtzWbRIMeh4i2SRXzi5neH2NcjR5s7wryCzsC0eD95yWGu9VBQR/BWIynGrPgAzJGtrPuEzBgfVhcA9HWSJn6uuICNB/YAA"
      }
    }
  },
  {
    "id": "dart-pet-hair",
    "src": "/work/dart-pet-hair-tall.7f02399a.webp",
    "width": 1080,
    "height": 1350,
    "alt": "Dodge Dart interior after dog hair extraction — mobile detailing in Harrisonburg VA",
    "vehicle": "Dodge Dart",
    "service": "Dog hair extraction",
    "crops": {
      "wide": {
        "src": "/work/dart-pet-hair-wide.4814e3ba.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAkAA4BaJZQC7ADp6Rx9xr9AAM1vA4QbLYy2mVj9h7jKE/IXsc9+vF0PJreGEqxR2Sdwf1Uez6EEA8KTMnxSP/O++7nS5UbL3EXgAAA="
      },
      "tall": {
        "src": "/work/dart-pet-hair-tall.7f02399a.webp",
        "width": 1080,
        "height": 1350,
        "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JZQAD4wH1rNvJOMcLSoS3pAD+H8ieP+GThh0YAVAiV8U3+Arii9dspAC07iLmFB9uUNluG6bnNW+ztjQ3oGA22zGWL+FXkr91/Ym42csje9KVjStV2P3Nj9/nfCKAX+gyQAAA"
      },
      "square": {
        "src": "/work/dart-pet-hair-square.f44db995.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQABAAA4BaJZQAAxe4fdsKlOAA/jNOBHY0iuXSj+lMQh1on1fAbF3NS4TV4tm04O5cVdsni57AHnd56E1wtUwI498MJXJmjpI9FLV7u9NR266a7hAAAA=="
      }
    }
  },
  {
    "id": "exterior-trim-restoration",
    "src": "/work/exterior-trim-restoration-tall.a06a8c53.webp",
    "width": 1080,
    "height": 1350,
    "alt": "White Jeep Wrangler after an exterior wash and plastic trim restoration — mobile detailing in Harrisonburg VA",
    "vehicle": "Jeep Wrangler",
    "service": "Exterior wash + plastic trim restoration + standard interior",
    "crops": {
      "wide": {
        "src": "/work/exterior-trim-restoration-wide.1b3d136b.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoQAAkAA4BaJZwAD4xu0zQcx/gA/qZ/qSqMIos3MLxbgMcvSrjsApzpelkxBTxNLCLFO2elOjB0yVi+UKfypLKx14Lv+X0S0qC0GLcrwIAAAA=="
      },
      "tall": {
        "src": "/work/exterior-trim-restoration-tall.a06a8c53.webp",
        "width": 1080,
        "height": 1350,
        "blurDataURL": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZQC7AYuk31TcICP1RknMAP6XdJmhN1Tl7tFIJU9smKQBmQ1HC33T0R3JYr9psIXAIfrpjVDx0kCchWzpWrj3S70GifXP+scGaWHcMom4tLeOdK+35QTEZkap/Q75uKBwMzEOUliroAAA"
      },
      "square": {
        "src": "/work/exterior-trim-restoration-square.e081b8dc.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABQAgCdASoQABAAA4BaJZQCdAYp5y4PiQvAuoAA/lvxYGq7MU9XbpWYejRcsoL/HKiILh4jngU53kBHpxI+ygfrEyvqclm4mCagEcyB5bbb/Dj2sFeGSd0oqCVvTTN1Ei77AxyqNuNSAAAA"
      }
    }
  },
  {
    "id": "f150-noahs-truck",
    "src": "/work/f150-noahs-truck-tall.2035d572.webp",
    "width": 673,
    "height": 841,
    "alt": "Noah's white Ford F-150, freshly washed — Noah's Detailing, mobile detailing in Harrisonburg VA",
    "vehicle": "Noah's white Ford F-150",
    "service": "Wash & wax",
    "crops": {
      "wide": {
        "src": "/work/f150-noahs-truck-wide.60e42e8e.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkAA4BaJZQCdADMJiyj0AD5djxoP3m2Fl2r/6exwr86/WaeghRqwlxfQmHK0h6C3zdmHkOm+U9yMB7ML2Q4nqxQAA=="
      },
      "tall": {
        "src": "/work/f150-noahs-truck-tall.2035d572.webp",
        "width": 673,
        "height": 841,
        "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JYwCo9B51VM/xoIwBtAAA/NQbdfezdWBwGu2R1QO2CpAuuY/bF95nEVZsxVgqHNVLPI7IZejg4I2gifszruvlhC1nY94LUXYFCGRjZdWxF3JjxbleYnC0K9YZtgAA"
      },
      "square": {
        "src": "/work/f150-noahs-truck-square.ab08d1bf.webp",
        "width": 841,
        "height": 841,
        "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQAgCdASoQABAAA4BaJQBOgMX/hPYwkl3YAP3isEBZIT9Vl5mEI20af3wyluE/GMuEnzfE0UsfSsK8+F/N+9zslej72VqeoQXTyWUabaH+LL4Qzhw9nbbKqFP/ZpylCcvRkbkgAAA="
      }
    }
  },
  {
    "id": "farm-trailers",
    "src": "/work/farm-trailers-tall.c3081b9d.webp",
    "width": 1080,
    "height": 1350,
    "alt": "White farm trailers after a wash — mobile detailing in Harrisonburg VA",
    "vehicle": "Farm trailers",
    "service": "Trailer wash",
    "crops": {
      "wide": {
        "src": "/work/farm-trailers-wide.d718b7bf.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAkAA4BaJQBOgBozniOjEAD9AndOVsT7RlaZ/5oslStITySs6pyBUSr6I3+dXD/hm8wAWhjFDK4vf+RT6tjq+cA2HTwy485uwoAA"
      },
      "tall": {
        "src": "/work/farm-trailers-tall.c3081b9d.webp",
        "width": 1080,
        "height": 1350,
        "blurDataURL": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBYdg1w+9Y4x01/6ej8QAPy0E157S+CC9p5MUIQ7gM3FaVvc5fXVWK8tQgvG6Nm/QI7aRZb7jY6Cw7wyFkwEv7z0VtHef4LXMw2ycxiSpeLnCvLPwMOt3HaHEcK3EmXFsSqYsRrXQ3WV3XN+IAAA"
      },
      "square": {
        "src": "/work/farm-trailers-square.1da9decb.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQAgCdASoQABAAA4BaJagCdAYxE43pCW6AAP4BMIWed/3mi0Xua57e+qKmQiiq5WFzAZRFGZLP+z8UxZClph91yA4xzgkty4ejkEhNlhqPVM3wFof70geRQiJvcVyNNVtpid93vPIefG8BiFDQ6h1tnqHg4AAA"
      }
    }
  },
  {
    "id": "headlight-after",
    "src": "/work/headlight-after-tall.ba004f33.webp",
    "width": 477,
    "height": 596,
    "alt": "Headlights after headlight restoration — mobile detailing in Harrisonburg VA",
    "vehicle": "Headlights",
    "service": "Headlight restoration",
    "stage": "after",
    "crops": {
      "wide": {
        "src": "/work/headlight-after-wide.c8b52a65.webp",
        "width": 524,
        "height": 295,
        "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJQBOgB9PAAt7AAD9xkYr5QD/KqXt4Xj7seRGBxU/fF0Fr+2gIY0yRDoHXcmwau6sRRR7NE+8YDcAAAA="
      },
      "tall": {
        "src": "/work/headlight-after-tall.ba004f33.webp",
        "width": 477,
        "height": 596,
        "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JQBWAA9XF/DqQT0G2SWh3gAD+g8/rPM+BmBfBPIXiXQRZ00171go4z/byVGyXUW5AtzepnVdGwGZtjLebqCcWp908XFdE45IUWy5oSLYALrZZ+wfmgAAA"
      },
      "square": {
        "src": "/work/headlight-after-square.60a1ff39.webp",
        "width": 524,
        "height": 524,
        "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQABAAA4BaJYgCdAEO523h6bAoAP4nHam6p/GNbsV8Ryb6tWDqZpcj6Ebvei70n74ueEdE7OPEq2rcoMooqGlXbk18z+Z9VXlu+uVCxUqUuQ8zFObnwAAA"
      }
    }
  },
  {
    "id": "headlight-before",
    "src": "/work/headlight-before-tall.cba6fcea.webp",
    "width": 477,
    "height": 596,
    "alt": "Headlights before headlight restoration — mobile detailing in Harrisonburg VA",
    "vehicle": "Headlights",
    "service": "Headlight restoration",
    "stage": "before",
    "crops": {
      "wide": {
        "src": "/work/headlight-before-wide.ee870176.webp",
        "width": 524,
        "height": 295,
        "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAkAA4BaJQBOgBww9j5ggAD9nKIYKntGf4syqdt6LpPjOjdyOClMI09faJFzaY5XKMRhdJSWYAAA"
      },
      "tall": {
        "src": "/work/headlight-before-tall.cba6fcea.webp",
        "width": 477,
        "height": 596,
        "blurDataURL": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JQBOgBEBOvgYnzolgzzYAQAD9m7Eb96mggjLkHmPCiyNSLZBNQtpsDteX3hpBT+32v/K/ow9EEsGvnByBMWEsacyHbigKpXJ8eu2/Ld3ljcLmfMtvWr9mlQ1FYAAA"
      },
      "square": {
        "src": "/work/headlight-before-square.8c1832ae.webp",
        "width": 524,
        "height": 524,
        "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQABAAA4BaJQBOgCICWXPaKV/1AAD8IG54OHQOXUmaW+fvXCQS54YgbMUKmyseEh36w9ya3pQafGfbLsIqm41LWHW5MotsUyRqlAAzQW6wBxAA"
      }
    }
  },
  {
    "id": "jeep-extraction",
    "src": "/work/jeep-extraction-tall.9bcb9e90.webp",
    "width": 1080,
    "height": 1350,
    "alt": "Jeep interior console after a full interior detail and extraction — mobile detailing in Harrisonburg VA",
    "vehicle": "Jeep",
    "service": "Full interior + extraction",
    "crops": {
      "wide": {
        "src": "/work/jeep-extraction-wide.6e000238.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoQAAkAA4BaJaQAArAWN/P1QAD++Fqw2Fh+xjE3ZWYzl5Rkh6nShCCH74zq5SXbYuxBDVcU7wtElZCmhhyUxuuAAAA="
      },
      "tall": {
        "src": "/work/jeep-extraction-tall.9bcb9e90.webp",
        "width": 1080,
        "height": 1350,
        "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JaQAAWZy+xqyJoSgPl2tAAP7yoRPI/FQTLhTio8S5uPTRv6Sm860dZxBUAKnh0oNeIr2FeHUpF2NzV7iC+ZZckmxm/Gvx6jSDVKTVA/g3OOw08ztxEbwZeTyqiXwSqIAgAA=="
      },
      "square": {
        "src": "/work/jeep-extraction-square.3eb94ef4.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAgCdASoQABAAA4BaJaQAD5JvOijp1eSBrSAA/vhacfKOk4zfp1uxDs4kurDKYOtsxAMg9hcp7Vip4rr9ChmOrXu0VQSc+roBjNBCNiHelvEIXtw+yBXCUoNahERgAAA="
      }
    }
  },
  {
    "id": "miata-wash-wax",
    "src": "/work/miata-wash-wax-tall.36d69faa.webp",
    "width": 864,
    "height": 1080,
    "alt": "Green 1995 Mazda Miata after a wash and wax — mobile detailing in Harrisonburg VA",
    "vehicle": "1995 Mazda Miata",
    "service": "Wash & wax",
    "crops": {
      "wide": {
        "src": "/work/miata-wash-wax-wide.862c5fb3.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoQAAkAA4BaJZQAAurU2KhIAP68Ty5MwFXtnQcWKiVHgn4mlphP1rw6Lex3UZ3bngk6P1COqokjkG9BU9HR+TLkhKSNMggQAAA="
      },
      "tall": {
        "src": "/work/miata-wash-wax-tall.36d69faa.webp",
        "width": 864,
        "height": 1080,
        "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZQC2yCKFP7Xdh1otc0AA/tmJvQaHP/F+C8wSXI05sAbNB21THKHVpupiBEJE44e2ubCL2+rhnl+o6kGkLccgN1SAAA=="
      },
      "square": {
        "src": "/work/miata-wash-wax-square.831506a7.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQABAAA4BaJYwCdAYu5j6poyAAAP7pT1P1+zJfdK5x/NGLwfnGPlOLupjmwkwaPVU+FnBrJMf+SNAO0GTKAfPJhB/J77EXnENZ8N8K8PYDgn1jmgAAAA=="
      }
    }
  },
  {
    "id": "minivan-reset",
    "src": "/work/minivan-reset-tall.da22da30.webp",
    "width": 1080,
    "height": 1350,
    "alt": "Gray Honda minivan after a full reset — mobile detailing in Harrisonburg VA",
    "vehicle": "Honda minivan",
    "service": "Full reset",
    "crops": {
      "wide": {
        "src": "/work/minivan-reset-wide.24be33f6.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAkAA4BaJYgCdAEf5dT8PJQAAP7JVL6j+t0siZOeV5RU39X7RiP5nBQjjMK/emwq1Xj3KUrWCO6ylHfuYSMNSChzwAAA"
      },
      "tall": {
        "src": "/work/minivan-reset-tall.da22da30.webp",
        "width": 1080,
        "height": 1350,
        "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JYwCdMoCGABehbuhk9U7kPusAAP6UmtssPTwvIffPxbpgk7xzI7AxDFdsR2c6Pk0yqiuUqoa0AMn2/lS+wHHc0EvXrIlAbuW006YKxfkAAA=="
      },
      "square": {
        "src": "/work/minivan-reset-square.da30845b.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQABAAA4BaJYgCdAEf5dVlpw4gAP7JVL6j+t0siZOeV5RU39X7RiP5nBQjjMK/emxGeP9lQdQYdXTOCLK373C7asKUVhgehWuyDvwv1CSEOmV1AAA="
      }
    }
  },
  {
    "id": "ram3500-wash-wax",
    "src": "/work/ram3500-wash-wax-tall.b974041c.webp",
    "width": 648,
    "height": 810,
    "alt": "Black Ram 3500 after a wash and wax — mobile detailing in Harrisonburg VA",
    "vehicle": "Ram 3500",
    "service": "Wash & wax",
    "crops": {
      "wide": {
        "src": "/work/ram3500-wash-wax-wide.fa0306c4.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAkAA4BaJQAAW8e+yGgxfSgA3g954vsYSU7KYCighgRuso2YsqjwungvAU1+ocr7Q4aMyiHemxR0+Z6Dyd/AAAA="
      },
      "tall": {
        "src": "/work/ram3500-wash-wax-tall.b974041c.webp",
        "width": 648,
        "height": 810,
        "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBfuKAAPhs9i+jrBurCwAPQGPBnVk+WDFjG/07ol5+aYm6DF/zWu836eBoegCRQ63Teot01oy5kvJpbsz4QUxXaZj0PdEu9YezmuTUAwjDnFCAA="
      },
      "square": {
        "src": "/work/ram3500-wash-wax-square.ad26d68a.webp",
        "width": 810,
        "height": 810,
        "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABQAgCdASoQABAAA4BaJYgAD5Mtx7u7n9AHLgAA91D332qVdXemhc1/ABg/Pd75waIXWmseRSBoTnm6kLGi0eUJHtYIg7mdgWyxH4pLWkMph6SfGYuFQMP98pt39OsAAAA="
      }
    }
  },
  {
    "id": "stock-engine-bay",
    "src": "/work/stock-engine-bay-tall.9f45a178.webp",
    "width": 1600,
    "height": 2000,
    "alt": "Clean engine bay under an open hood",
    "vehicle": "",
    "service": "",
    "stock": true,
    "credit": "Unsplash — https://images.unsplash.com/photo-1606577924006-27d39b132ae2 (Unsplash License)",
    "crops": {
      "wide": {
        "src": "/work/stock-engine-bay-wide.6f4df4e8.webp",
        "width": 1800,
        "height": 1013,
        "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQAgCdASoQAAkAA4BaJbACdAEQC8wAU1oAAP7xl8GTnt6YOKJllXOFwUToMrHrYjovhHyyVhjo2bU94EDgZzKFJ4Nni7C1ERGSQ57CVtmkpqaOVKdvx/+QAAA="
      },
      "tall": {
        "src": "/work/stock-engine-bay-tall.9f45a178.webp",
        "width": 1600,
        "height": 2000,
        "blurDataURL": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAAAwBACdASoQABQAPu1iqU2ppaOiMAgBMB2JbAC7AywBz0+yrdz9RR72U9AA/u8l0/bULU1OHrop0I5LmGcPavp8tp2C4OIB/5p4g6CfD6Fzsp8k4vtc+ujitDJUr/yNtV6sNmOdf/56qPWnbQi5p8/tNIM2W8a25Fk34poYH3AOJEFxyFqM22/dnZQe8rPFedfInwe/f1UpdQAA"
      },
      "square": {
        "src": "/work/stock-engine-bay-square.635849d5.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABQAgCdASoQABAAA4BaJbAC7AYxFdDROP6DKzgA/vW/m2T0lQXTaH0xMI7bLwqsyRQ9sHtvlAalCxB9+501cviJ2TMrNKapqsQA6eDbaxYIJ49Z7j4AGtLyCjAyIw/Shxhmcpaqe/W6Iwy21PvLbRjdDyn6iNzouafnwAAA"
      }
    }
  },
  {
    "id": "stock-hero-pressure-wash",
    "src": "/work/stock-hero-pressure-wash-tall.4cb96b75.webp",
    "width": 1170,
    "height": 1463,
    "alt": "Black sports car being rinsed with a pressure washer, water spraying off glossy paint",
    "vehicle": "",
    "service": "",
    "stock": true,
    "credit": "Unsplash — https://images.unsplash.com/photo-1520340356584-f9917d1eea6f (Unsplash License)",
    "crops": {
      "wide": {
        "src": "/work/stock-hero-pressure-wash-wide.bf71d1c2.webp",
        "width": 2400,
        "height": 1350,
        "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAkAA4BaJZACdAEfli1UNYl0AP5sUgRYOmrFgVX2MEmtGOP1W4PAirPBTzOvvTf+frzCIinNaocfr4+Tek/2XknauoWGbF/dHQPmTa2pEAAA"
      },
      "tall": {
        "src": "/work/stock-hero-pressure-wash-tall.4cb96b75.webp",
        "width": 1170,
        "height": 1463,
        "blurDataURL": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAADQAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBWAAoq+nnWpc0usHgAA/sBR3njBVjqnULJM3LTgiwKSOCQqr+Un6Qzyis3S9lWGUARSw4gG3kjtumWlzJHfjUDTfzDVMUJuy8rG12nzXfgfFp1wA/8NuOjztqZxM6RT6z9b0W4QjYqrVgAAAA=="
      },
      "square": {
        "src": "/work/stock-hero-pressure-wash-square.3023ec42.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAQCdASoQABAAA4BaJYgCdACh/luCuFAA/vEEtvwmD57bncu/O2IDLW+T42E22RmBfzhK0vqZXCGvGABlhJvPBCbGuaXkm0ukrtQqSfE3Ta4EnHhsx1ZOti9tz1SsUf+/3euHh+goWok/NEQQAAAA"
      }
    }
  },
  {
    "id": "stock-interior",
    "src": "/work/stock-interior-tall.822b069b.webp",
    "width": 432,
    "height": 540,
    "alt": "Clean leather car seats and dashboard",
    "vehicle": "",
    "service": "",
    "stock": true,
    "credit": "StockSnap — https://cdn.stocksnap.io/img-thumbs/960w/SF6UIKA8HT.jpg (CC0)",
    "crops": {
      "wide": {
        "src": "/work/stock-interior-wide.3e7204a9.webp",
        "width": 960,
        "height": 540,
        "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAkAA4BaJYgC7AEPUvhEnTwAAP7uNay+aVXxJDwWdunlhWXGljpIbXMvn9xqq48rf/uSp9PMvbFI9zvf5Z3dFQfVv/AXq5BzzLwQFMIv+mTTyO7agAAA"
      },
      "tall": {
        "src": "/work/stock-interior-tall.822b069b.webp",
        "width": 432,
        "height": 540,
        "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JQBdgMY7WwebFac+vPf3AAP7oSfwb79wRCVP9t07MwlhhlN8gokukvkQTvzPuh04piCxbjg/HCspgMt358NmMI3niBSz1zS+P25LVBbDJGSAiVhlt87yy/LA7fpcftHKPKmQ2NJDiKhR0XVte3kkY/u3RHNKCmlc9OAAA"
      },
      "square": {
        "src": "/work/stock-interior-square.ca5d0a66.webp",
        "width": 540,
        "height": 540,
        "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwAgCdASoQABAAA4BaJQBdgMX1pMM4PSBIAAD+8H0s5vdTLqIU30nb0hlWbbmtnTfwzf2pnjJHRsJoPHkF4njaMjRZ8Wj+uPTOSNENVT8lq7Hlzjo+KOfFZ7NC5+PMUJzieeCCXO6Hj4YHgankmY6VohlR8GkAAAA="
      }
    }
  },
  {
    "id": "tractor",
    "src": "/work/tractor-tall.5e57bbbf.webp",
    "width": 1080,
    "height": 1350,
    "alt": "Large green tractor after an equipment detail — mobile detailing in Harrisonburg VA",
    "vehicle": "Large tractor",
    "service": "Equipment detail",
    "crops": {
      "wide": {
        "src": "/work/tractor-wide.dae33108.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAgCdASoQAAkAA4BaJagCdAYtpyKKcn2u9QAA/qsmZDZwJ/qM1r8TK1R/Nlh2mbVtkxfOK/gvJjYZPfi+pgMcWulolnqUuI8G1LzgAPvBpMLSgrm9I5gXgHn9JMWm9QWT4fVZiAAAAA=="
      },
      "tall": {
        "src": "/work/tractor-tall.5e57bbbf.webp",
        "width": 1080,
        "height": 1350,
        "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoQABQAPu1iqU2ppaOiMAgBMB2JYgC7ACHwyIO0XUW+Y5JiAAD+8f3HuClKy4WsbK1MDSR4k44cnlNRolfP9qL9p8ex4l6Rjpf3ExeTWwhIBOEyKVQ++mwp+dAVApNHqCOcoPs705CpxQcP+rWor/Zty0wpCueobcAAAA=="
      },
      "square": {
        "src": "/work/tractor-square.66cf1fa7.webp",
        "width": 1000,
        "height": 1000,
        "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABQAgCdASoQABAAA4BaJbACdAYulLdBBWoxpmAA/mq22Dc1xl4+3hlF+YQ6EB2FGt9QfnQQmfJyplZLR4EgwffcoBomOjJf0ris4FYPEfsjfgY4ZPfjHfYEy/2eeNQ73DJMIIpFDJPuk5VDxNhu1QqLX+AJHKywAAA="
      }
    }
  },
  {
    "id": "wrx-hand-wax",
    "src": "/work/wrx-hand-wax-tall.b4aaa7e3.webp",
    "width": 648,
    "height": 810,
    "alt": "Blue Subaru WRX after a hand wax — mobile detailing in Harrisonburg VA",
    "vehicle": "Subaru WRX",
    "service": "Hand wax",
    "crops": {
      "wide": {
        "src": "/work/wrx-hand-wax-wide.dacb404b.webp",
        "width": 1080,
        "height": 608,
        "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAQCdASoQAAkAA4BaJZQAAex+Y4qgAPshHDx51ESLN0r07uSH7Om+M7X0FeHwpzUbCmMcCN7s/KvwNNcwmo4pjbvL6dflIzW/5QAA"
      },
      "tall": {
        "src": "/work/wrx-hand-wax-tall.b4aaa7e3.webp",
        "width": 648,
        "height": 810,
        "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoQABQAPu1iqU2ppaOiMAgBMB2JZQDG9CLE4Zm2ZmN6DRUAAPfNjlUQ+0RahXUi82LdJP7ne9PYBqUSQAsSSzkwpdt8NYPSMpbcp1rDx9ijyAF2DZxD8yT3aNB2+Anon0G0+uQB+gAAAA=="
      },
      "square": {
        "src": "/work/wrx-hand-wax-square.00d449db.webp",
        "width": 810,
        "height": 810,
        "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAQCdASoQABAAA4BaJZQAAsUYvRkAAPRrqAiwbdMTjitB1IH0z8rFVDp8YiwZjXjGWR0fjXzpA1vtfn/4n6znkrhfabiVQDyNXQ5LPnY2K3OrzH4vId7onbFN+ZoCAAA="
      }
    }
  }
];

const byId = (id: string) => photos.find((p) => p.id === id)!;

export const pairs: PhotoPair[] = [
  { id: "headlight", vehicle: "Headlights", service: "Headlight restoration", before: byId("headlight-before"), after: byId("headlight-after") },
];
