// AUTO-GENERATED by scripts/process-images.mjs — do not edit by hand. Run `npm run images`.
import type { Photo, PhotoPair } from "@/lib/photo-types";

export const photos: Photo[] = [];

export const pairs: PhotoPair[] = [];
